---
title: "R Notebook"
output: html_notebook
---



```{r}
library(readxl)


    dat <- read_xlsx("Data Keuangan Bank BRI.xlsx")
    
    dat <- as.data.frame(dat)
    
    
    print(dat)
```


```{r}
dat_proses <- dat[c(2,3,4,5,6,7,8,9)]

dat_proses
```





```{r}
library(corrplot)

korelasi <- cor(dat_proses)

corrplot(korelasi, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45,
         addCoef.col = 1,
         number.cex = .7)


```




```{r}


dataku <- dat[c("Tahun", "ROA (%)", "ROE (%)")]

susun_data = reshape2::melt(data = dataku, id.vars = c("Tahun")   )
    
susun_data
```


```{r}

   gambar <-  ggplot(susun_data, aes(x = Tahun, y = value, fill = variable))+
      facet_wrap( ~variable,  scales = "free",  ncol = 1) +
       geom_line(color="turquoise4") +
       theme_minimal() 
    

gambar
    

```



```{r}
library(ggplot2)




p <- ggplot(data = NULL, aes(x = x, y = y)) +
       geom_line(color="turquoise4") +
       theme_minimal() + 
       labs(x="", y="Sales", title="Total Sales (Past 100 Days)") +
       theme(plot.title = element_text(hjust=0.5, size=20, face="bold"))


p
```





```{r}
    dat <- read_xlsx("Data Keuangan Bank BRI.xlsx")
    
    dat <- as.data.frame(dat)
    
    dat_proses <- dat[c(1,2,3,4,5,6,7,8,9)]
    

dat_VECM <- dat_proses[c("NPL (%)", "Earning per Share (Rp)")]

dat_VECM

```


```{r}
library(urca)

Tstat <- vector(mode = "numeric")
Tkritis <- vector(mode = "numeric")
kesimpulan <- vector(mode = "character")

nama <- colnames(dat_VECM)


for(i in 1 : length(nama))
{
X <- dat_VECM[,i]

hasil = urca::ur.df(X, type = c("none"),
lags = 0, selectlags = "AIC")

#hasil@teststat

#hasil@cval

Tstat[i] <- hasil@teststat
Tkritis[i] <- hasil@cval[2]

if(abs(Tstat[i]) < abs(Tkritis[i]))
{
  
  kalimat = paste0("Data pada Variabel ", nama[i] , " Tidak Stasioner pada Level")
  kesimpulan[i] <- kalimat
  
}

if(abs(Tstat[i]) > abs(Tkritis[i]))
{
  
  kalimat = paste0("Data pada Variabel ", nama[i] , " Stasioner pada Level")
  kesimpulan[i] <- kalimat
  
}










}


dframe <- data.frame(nama, Tstat, Tkritis, kesimpulan)
colnames(dframe) <- c("Variabel", "Statistik T", "Nilai Kritis T pada Tingkat Signifikansi 5%", "Kesimpulan")

dframe


```






```{r}
library(urca)

Tstat <- vector(mode = "numeric")
Tkritis <- vector(mode = "numeric")
kesimpulan <- vector(mode = "character")

nama <- colnames(dat_VECM)


for(i in 1 : length(nama))
{
X <- dat_VECM[,i]
X <- diff(X)

hasil = urca::ur.df(X, type = c("none"),
lags = 0, selectlags = "AIC")

#hasil@teststat

#hasil@cval

Tstat[i] <- hasil@teststat
Tkritis[i] <- hasil@cval[2]

if(abs(Tstat[i]) < abs(Tkritis[i]))
{
  
  kalimat = paste0("Data pada Variabel ", nama[i] , " Tidak Stasioner pada First Difference")
  kesimpulan[i] <- kalimat
  
}

if(abs(Tstat[i]) > abs(Tkritis[i]))
{
  
  kalimat = paste0("Data pada Variabel ", nama[i] , " Stasioner pada First Difference")
  kesimpulan[i] <- kalimat
  
}










}


dframe <- data.frame(nama, Tstat, Tkritis, kesimpulan)
colnames(dframe) <- c("Variabel", "Statistik T", "Nilai Kritis T pada Tingkat Signifikansi 5%", "Kesimpulan")

dframe


```


















